### ISSUE TITLE
Logging in with divio results in KeyError 'email'

### ISSUE THREAD

**Issue by victor-yunenko** [divio/aldryn-sso#68]
It looks like user_data didn't contain an email:

It was equal to:
```
user_data =  {first_name: 'Anastasiia', is_active: True, is_staff: True, is_superuser: True, last_name: 'Kuvshinova'}
```

Hence `email=user_data.pop('email')` raises an error. I wonder whether it can be divio sso issue?

That's related to https://github.com/divio/aldryn-sso/pull/67

**Comment by macolo** [comment]
Here is the link to the code that errors out: https://github.com/divio/aldryn-sso/blob/dc56e9ef921141f53dfeeb11a9a6434a647ffc8a/aldryn_sso/sso.py#L106

**Comment by macolo** [comment]
Typical error screen:

![keyerror_at_aldryn_sso_login_authenticate](https://user-images.githubusercontent.com/4056979/90399256-f9473400-e09a-11ea-9df5-2e12a5a21850.jpg)

**Comment by macolo** [comment]
@GaretJax I wasnt able to figure out from where `build_user()` is executed, it doesnt appear to be part of the project 🤔 

![image](https://user-images.githubusercontent.com/4056979/90400886-77a4d580-e09d-11ea-82bc-51400798223b.png)

**Comment by victor-yunenko** [comment]
It's been resolved 👌
